apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: repo-label-runner-deploy
spec:
  replicas: 1
  template:
    spec:
      repository: uoio1/aks_runner
      labels:
        - custom-runner