apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: namespace-runner-deploy
  namespace: arc
spec:
  replicas: 1
  template:
    spec:
      repository: uoio1/aks_runner
      labels:
        - custom-runner