---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners-linux
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      repository: uoio1/aks_runner
      labels:
        - linux
        - X64
        - test-linux