name: Docker Workflow
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ["self-hosted","linux","test-linux"]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2 
    - name: Echo Hello World
      run: echo "hello world"



